### ISSUE TITLE
弹幕下载失败

### ISSUE THREAD

**Issue by agbghewtjedgf** [koharubiyori/nicomment#7]
nico回歸後似乎又遇到問題了
![2024-08-25](https://github.com/user-attachments/assets/7ae6bdf9-1695-4cf3-87e3-a050e8ea14d5)

**Comment by koharubiyori** [comment]
nico回归后使用了更严格的IP防火墙，我的T连不上去，暂时没办法修复

**Comment by koharubiyori** [comment]
已修复

**Comment by agbghewtjedgf** [comment]
> 已修复

謝謝，已恢復正常使用
